MaquinaBebidas: Core/Src/core.c File Reference
core.c File Reference
#include "main.h"
#include "lcd.h"
#include "modules.h"
#include "core.h"
Functions
int read_type_of_capsule (int code1, int code2, int code3)
void preparing (int type, ADC_HandleTypeDef *hadc1)
Function Documentation
preparing()
void preparing (int type, ADC_HandleTypeDef * hadc1)
Definition at line 53 of file core.c.
References add_co2(), ADD_Pin, add_water(), CONFIRM_Pin, cooler(), GPIOB, hadc1, HAL_Delay(), HAL_GPIO_ReadPin(), heater(), LCD_Clear(), LCD_String_xy(), and SUB_Pin.
Referenced by main().
read_type_of_capsule()
int read_type_of_capsule (int code1, int code2, int code3)
Definition at line 12 of file core.c.
References LCD_Clear(), and LCD_String_xy().
Referenced by main().