MaquinaBebidas: Core/Src/lcd.c File Reference
lcd.c File Reference
#include "main.h"
#include "lcd.h"
Functions
void writePort (char x)
void LCD_Init ()
void LCD_Clear ()
void LCD_Command (char cmd)
void LCD_Char (char dat)
void LCD_String (const char *msg)
void LCD_Custom_Char (unsigned char loc, unsigned char *msg)
void LCD_String_xy (char row, char pos, const char *msg)
Variables
unsigned char acomacento [8]
unsigned char acomtil [8]
unsigned char cedilha [8]
unsigned char ecomacento [8]
unsigned char ocomtil [8]
unsigned char ocomacento [8]
unsigned char grausimbolo [8]
char aacentuado [2] = "á"
char eacentuado [2] = "é"
char otil [2] = "õ"
char atil [2] = "ã"
char ccedilha [2] = "ç"
char oacentuado [2] = "ó"
char grau [2] = "°"
Function Documentation
LCD_Char()
void LCD_Char (char dat)
Definition at line 151 of file lcd.c.
References GPIO_PIN_8, GPIO_PIN_9, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), and writePort().
Referenced by LCD_Custom_Char(), and LCD_String().
LCD_Clear()
void LCD_Clear ()
Definition at line 135 of file lcd.c.
References LCD_Command().
Referenced by add_co2(), cooler(), heater(), main(), preparing(), and read_type_of_capsule().
LCD_Command()
void LCD_Command (char cmd)
Definition at line 140 of file lcd.c.
References GPIO_PIN_8, GPIO_PIN_9, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), and writePort().
Referenced by LCD_Clear(), LCD_Custom_Char(), LCD_Init(), and LCD_String_xy().
LCD_Custom_Char()
void LCD_Custom_Char (unsigned char loc, unsigned char * msg)
Definition at line 201 of file lcd.c.
References LCD_Char(), and LCD_Command().
Referenced by LCD_Init().
LCD_Init()
void LCD_Init ()
Definition at line 118 of file lcd.c.
References acomacento, acomtil, cedilha, ecomacento, grausimbolo, HAL_Delay(), LCD_Command(), LCD_Custom_Char(), ocomacento, and ocomtil.
Referenced by main().
LCD_String()
void LCD_String (const char * msg)
Definition at line 161 of file lcd.c.
References aacentuado, atil, ccedilha, eacentuado, grau, LCD_Char(), oacentuado, and otil.
Referenced by LCD_String_xy().
LCD_String_xy()
void LCD_String_xy (char row, char pos, const char * msg)
Definition at line 212 of file lcd.c.
References LCD_Command(), and LCD_String().
Referenced by add_co2(), add_water(), cooler(), heater(), main(), preparing(), and read_type_of_capsule().
writePort()
void writePort (char x)
Definition at line 97 of file lcd.c.
References GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIOA, GPIOB, and HAL_GPIO_WritePin().
Referenced by LCD_Char(), and LCD_Command().
Variable Documentation
aacentuado
char aacentuado[2] = "á"
Definition at line 88 of file lcd.c.
Referenced by LCD_String().
acomacento
unsigned char acomacento[8]
Initial value:
= {
    0b00010,
    0b00100,
    0b01110,
    0b00001,
    0b01111,
    0b10001,
    0b01111,
    0b00000
}
Definition at line 10 of file lcd.c.
Referenced by LCD_Init().
acomtil
unsigned char acomtil[8]
Initial value:
= {
    0b01110,
    0b00000,
    0b01110,
    0b00001,
    0b01111,
    0b10001,
    0b01111,
    0b00000
}
Definition at line 21 of file lcd.c.
Referenced by LCD_Init().
atil
char atil[2] = "ã"
Definition at line 91 of file lcd.c.
Referenced by LCD_String().
ccedilha
char ccedilha[2] = "ç"
Definition at line 92 of file lcd.c.
Referenced by LCD_String().
cedilha
unsigned char cedilha[8]
Initial value:
= {
    0b00000,
    0b01111,
    0b10000,
    0b10000,
    0b10000,
    0b01111,
    0b00100,
    0b00100
}
Definition at line 32 of file lcd.c.
Referenced by LCD_Init().
eacentuado
char eacentuado[2] = "é"
Definition at line 89 of file lcd.c.
Referenced by LCD_String().
ecomacento
unsigned char ecomacento[8]
Initial value:
= {
    0b00010,
    0b00100,
    0b01110,
    0b10001,
    0b11111,
    0b10000,
    0b01111,
    0b00000
}
Definition at line 43 of file lcd.c.
Referenced by LCD_Init().
grau
char grau[2] = "°"
Definition at line 94 of file lcd.c.
Referenced by LCD_String().
grausimbolo
unsigned char grausimbolo[8]
Initial value:
= {
  0b01110,
  0b01010,
  0b01110,
  0b00000,
  0b00000,
  0b00000,
  0b00000,
  0b00000
}
Definition at line 76 of file lcd.c.
Referenced by LCD_Init().
oacentuado
char oacentuado[2] = "ó"
Definition at line 93 of file lcd.c.
Referenced by LCD_String().
ocomacento
unsigned char ocomacento[8]
Initial value:
= {
  0b00010,
  0b00100,
  0b01110,
  0b10001,
  0b10001,
  0b10001,
  0b01110,
  0b00000
}
Definition at line 65 of file lcd.c.
Referenced by LCD_Init().
ocomtil
unsigned char ocomtil[8]
Initial value:
= {
    0b01110,
    0b00000,
    0b01110,
    0b10001,
    0b10001,
    0b10001,
    0b01110,
    0b00000
}
Definition at line 54 of file lcd.c.
Referenced by LCD_Init().
otil
char otil[2] = "õ"
Definition at line 90 of file lcd.c.
Referenced by LCD_String().