MaquinaBebidas: Core/Inc/lcd.h File Reference
lcd.h File Reference
#include <stdint.h>
#include <stdio.h>
#include "main.h"
Functions
void LCD_Init ()
void LCD_Command (char)
void LCD_Char (char x)
void LCD_String (const char *)
void LCD_String_xy (char, char, const char *)
void LCD_Custom_Char (unsigned char loc, unsigned char *msg)
void LCD_Clear ()
Function Documentation
LCD_Char()
void LCD_Char (char x)
Definition at line 151 of file lcd.c.
References GPIO_PIN_8, GPIO_PIN_9, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), and writePort().
Referenced by LCD_Custom_Char(), and LCD_String().
LCD_Clear()
void LCD_Clear ()
Definition at line 135 of file lcd.c.
References LCD_Command().
Referenced by cooler(), heater(), main(), preparing(), and read_type_of_capsule().
LCD_Command()
void LCD_Command (char)
Definition at line 140 of file lcd.c.
References GPIO_PIN_8, GPIO_PIN_9, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), and writePort().
Referenced by LCD_Clear(), LCD_Custom_Char(), LCD_Init(), and LCD_String_xy().
LCD_Custom_Char()
void LCD_Custom_Char (unsigned char loc, unsigned char * msg)
Definition at line 201 of file lcd.c.
References LCD_Char(), and LCD_Command().
Referenced by LCD_Init().
LCD_Init()
void LCD_Init ()
Definition at line 118 of file lcd.c.
References acomacento, acomtil, cedilha, ecomacento, grausimbolo, HAL_Delay(), LCD_Command(), LCD_Custom_Char(), ocomacento, and ocomtil.
Referenced by main().
LCD_String()
void LCD_String (const char *)
Definition at line 161 of file lcd.c.
References aacentuado, atil, ccedilha, eacentuado, grau, LCD_Char(), oacentuado, and otil.
Referenced by LCD_String_xy().
LCD_String_xy()
void LCD_String_xy (char , char , const char *)
Definition at line 212 of file lcd.c.
References LCD_Command(), and LCD_String().
Referenced by add_co2(), add_water(), cooler(), heater(), main(), preparing(), and read_type_of_capsule().