MaquinaBebidas: Core/Inc/main.h File Reference
main.h File Reference
: Header for main.c file. This file contains the common defines of the application.
#include "stm32f1xx_hal.h"
Macros
#define PRESS_WATER_Pin GPIO_PIN_14
#define PRESS_WATER_GPIO_Port GPIOC
#define PRESS_CO2_Pin GPIO_PIN_15
#define PRESS_CO2_GPIO_Port GPIOC
#define READ_Pin GPIO_PIN_7
#define READ_GPIO_Port GPIOA
#define VALV_WATER_Pin GPIO_PIN_0
#define VALV_WATER_GPIO_Port GPIOB
#define VALV_CO2_Pin GPIO_PIN_1
#define VALV_CO2_GPIO_Port GPIOB
#define VALV_HOT_WATER_Pin GPIO_PIN_10
#define VALV_HOT_WATER_GPIO_Port GPIOB
#define VALV_COLD_WATER_Pin GPIO_PIN_11
#define VALV_COLD_WATER_GPIO_Port GPIOB
#define CANCEL_Pin GPIO_PIN_12
#define CANCEL_GPIO_Port GPIOB
#define ADD_Pin GPIO_PIN_13
#define ADD_GPIO_Port GPIOB
#define SUB_Pin GPIO_PIN_14
#define SUB_GPIO_Port GPIOB
#define CONFIRM_Pin GPIO_PIN_15
#define CONFIRM_GPIO_Port GPIOB
#define OPT_READ1_Pin GPIO_PIN_8
#define OPT_READ1_GPIO_Port GPIOA
#define OPT_READ2_Pin GPIO_PIN_9
#define OPT_READ2_GPIO_Port GPIOA
#define OPT_READ3_Pin GPIO_PIN_10
#define OPT_READ3_GPIO_Port GPIOA
#define B0_Pin GPIO_PIN_11
#define B0_GPIO_Port GPIOA
#define B1_Pin GPIO_PIN_12
#define B1_GPIO_Port GPIOA
#define B2_Pin GPIO_PIN_15
#define B2_GPIO_Port GPIOA
#define B3_Pin GPIO_PIN_3
#define B3_GPIO_Port GPIOB
#define B4_Pin GPIO_PIN_4
#define B4_GPIO_Port GPIOB
#define B5_Pin GPIO_PIN_5
#define B5_GPIO_Port GPIOB
#define B6_Pin GPIO_PIN_6
#define B6_GPIO_Port GPIOB
#define B7_Pin GPIO_PIN_7
#define B7_GPIO_Port GPIOB
#define RS_Pin GPIO_PIN_8
#define RS_GPIO_Port GPIOB
#define E_Pin GPIO_PIN_9
#define E_GPIO_Port GPIOB
Functions
void HAL_TIM_MspPostInit (TIM_HandleTypeDef *htim)
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Attention
© Copyright (c) 2020 STMicroelectronics. All rights reserved.
This software component is licensed by ST under BSD 3-Clause license, the "License"; You may not use this file except in compliance with the License. You may obtain a copy of the License at: opensource.org/licenses/BSD-3-Clause
Definition in file main.h.
Macro Definition Documentation
ADD_GPIO_Port
#define ADD_GPIO_Port GPIOB
Definition at line 80 of file main.h.
ADD_Pin
#define ADD_Pin GPIO_PIN_13
Definition at line 79 of file main.h.
B0_GPIO_Port
#define B0_GPIO_Port GPIOA
Definition at line 92 of file main.h.
B0_Pin
#define B0_Pin GPIO_PIN_11
Definition at line 91 of file main.h.
B1_GPIO_Port
#define B1_GPIO_Port GPIOA
Definition at line 94 of file main.h.
B1_Pin
#define B1_Pin GPIO_PIN_12
Definition at line 93 of file main.h.
B2_GPIO_Port
#define B2_GPIO_Port GPIOA
Definition at line 96 of file main.h.
B2_Pin
#define B2_Pin GPIO_PIN_15
Definition at line 95 of file main.h.
B3_GPIO_Port
#define B3_GPIO_Port GPIOB
Definition at line 98 of file main.h.
B3_Pin
#define B3_Pin GPIO_PIN_3
Definition at line 97 of file main.h.
B4_GPIO_Port
#define B4_GPIO_Port GPIOB
Definition at line 100 of file main.h.
B4_Pin
#define B4_Pin GPIO_PIN_4
Definition at line 99 of file main.h.
B5_GPIO_Port
#define B5_GPIO_Port GPIOB
Definition at line 102 of file main.h.
B5_Pin
#define B5_Pin GPIO_PIN_5
Definition at line 101 of file main.h.
B6_GPIO_Port
#define B6_GPIO_Port GPIOB
Definition at line 104 of file main.h.
B6_Pin
#define B6_Pin GPIO_PIN_6
Definition at line 103 of file main.h.
B7_GPIO_Port
#define B7_GPIO_Port GPIOB
Definition at line 106 of file main.h.
B7_Pin
#define B7_Pin GPIO_PIN_7
Definition at line 105 of file main.h.
CANCEL_GPIO_Port
#define CANCEL_GPIO_Port GPIOB
Definition at line 78 of file main.h.
CANCEL_Pin
#define CANCEL_Pin GPIO_PIN_12
Definition at line 77 of file main.h.
CONFIRM_GPIO_Port
#define CONFIRM_GPIO_Port GPIOB
Definition at line 84 of file main.h.
CONFIRM_Pin
#define CONFIRM_Pin GPIO_PIN_15
Definition at line 83 of file main.h.
E_GPIO_Port
#define E_GPIO_Port GPIOB
Definition at line 110 of file main.h.
E_Pin
#define E_Pin GPIO_PIN_9
Definition at line 109 of file main.h.
OPT_READ1_GPIO_Port
#define OPT_READ1_GPIO_Port GPIOA
Definition at line 86 of file main.h.
OPT_READ1_Pin
#define OPT_READ1_Pin GPIO_PIN_8
Definition at line 85 of file main.h.
OPT_READ2_GPIO_Port
#define OPT_READ2_GPIO_Port GPIOA
Definition at line 88 of file main.h.
OPT_READ2_Pin
#define OPT_READ2_Pin GPIO_PIN_9
Definition at line 87 of file main.h.
OPT_READ3_GPIO_Port
#define OPT_READ3_GPIO_Port GPIOA
Definition at line 90 of file main.h.
OPT_READ3_Pin
#define OPT_READ3_Pin GPIO_PIN_10
Definition at line 89 of file main.h.
PRESS_CO2_GPIO_Port
#define PRESS_CO2_GPIO_Port GPIOC
Definition at line 66 of file main.h.
PRESS_CO2_Pin
#define PRESS_CO2_Pin GPIO_PIN_15
Definition at line 65 of file main.h.
PRESS_WATER_GPIO_Port
#define PRESS_WATER_GPIO_Port GPIOC
Definition at line 64 of file main.h.
PRESS_WATER_Pin
#define PRESS_WATER_Pin GPIO_PIN_14
Definition at line 63 of file main.h.
READ_GPIO_Port
#define READ_GPIO_Port GPIOA
Definition at line 68 of file main.h.
READ_Pin
#define READ_Pin GPIO_PIN_7
Definition at line 67 of file main.h.
RS_GPIO_Port
#define RS_GPIO_Port GPIOB
Definition at line 108 of file main.h.
RS_Pin
#define RS_Pin GPIO_PIN_8
Definition at line 107 of file main.h.
SUB_GPIO_Port
#define SUB_GPIO_Port GPIOB
Definition at line 82 of file main.h.
SUB_Pin
#define SUB_Pin GPIO_PIN_14
Definition at line 81 of file main.h.
VALV_CO2_GPIO_Port
#define VALV_CO2_GPIO_Port GPIOB
Definition at line 72 of file main.h.
VALV_CO2_Pin
#define VALV_CO2_Pin GPIO_PIN_1
Definition at line 71 of file main.h.
VALV_COLD_WATER_GPIO_Port
#define VALV_COLD_WATER_GPIO_Port GPIOB
Definition at line 76 of file main.h.
VALV_COLD_WATER_Pin
#define VALV_COLD_WATER_Pin GPIO_PIN_11
Definition at line 75 of file main.h.
VALV_HOT_WATER_GPIO_Port
#define VALV_HOT_WATER_GPIO_Port GPIOB
Definition at line 74 of file main.h.
VALV_HOT_WATER_Pin
#define VALV_HOT_WATER_Pin GPIO_PIN_10
Definition at line 73 of file main.h.
VALV_WATER_GPIO_Port
#define VALV_WATER_GPIO_Port GPIOB
Definition at line 70 of file main.h.
VALV_WATER_Pin
#define VALV_WATER_Pin GPIO_PIN_0
Definition at line 69 of file main.h.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 647 of file main.c.
Referenced by HAL_ADC_MspInit(), MX_ADC1_Init(), MX_TIM2_Init(), MX_TIM3_Init(), MX_TIM4_Init(), and SystemClock_Config().
HAL_TIM_MspPostInit()
void HAL_TIM_MspPostInit (TIM_HandleTypeDef * htim)
TIM2 GPIO Configuration PA0-WKUP ---—> TIM2_CH1 PA1 ---—> TIM2_CH2 PA2 ---—> TIM2_CH3
TIM2 GPIO Configuration PA0-WKUP ---—> TIM2_CH1 PA1 ---—> TIM2_CH2 PA2 ---—> TIM2_CH3
Definition at line 218 of file stm32f1xx_hal_msp.c.
References __HAL_RCC_GPIOA_CLK_ENABLE, GPIO_MODE_AF_PP, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_SPEED_FREQ_LOW, GPIOA, HAL_GPIO_Init(), TIM_HandleTypeDef::Instance, GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Speed, and TIM2.
Referenced by MX_TIM2_Init().