MaquinaBebidas: Core/Inc/modules.h File Reference
modules.h File Reference
#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "lcd.h"
Functions
void add_water (int time, int type)
void heater (float desired_temperature, ADC_HandleTypeDef *hadc1)
void cooler (float desired_temperature, ADC_HandleTypeDef *hadc1)
void add_co2 (int time)
Function Documentation
add_co2()
void add_co2 (int time)
Definition at line 45 of file modules.c.
References GPIO_PIN_1, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOB, GPIOC, HAL_Delay(), HAL_GPIO_ReadPin(), HAL_GPIO_WritePin(), LCD_Clear(), LCD_String_xy(), and PRESS_CO2_Pin.
Referenced by preparing().
add_water()
void add_water (int time, int type)
Definition at line 22 of file modules.c.
References dutyCycle, GPIO_PIN_0, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), LCD_String_xy(), and TIM2.
Referenced by preparing().
cooler()
void cooler (float desired_temperature, ADC_HandleTypeDef * hadc1)
Definition at line 104 of file modules.c.
References adc2, ADC_SCALE, adcData, CONVERSION, DEGREE_CONVERSION, flag, hadc1, HAL_ADC_Start_DMA(), HAL_Delay(), LCD_Clear(), LCD_String_xy(), temperature2, and TIM2.
Referenced by preparing().
heater()
void heater (float desired_temperature, ADC_HandleTypeDef * hadc1)
Definition at line 64 of file modules.c.
References adc1, ADC_SCALE, adcData, CONVERSION, DEGREE_CONVERSION, flag, hadc1, HAL_ADC_Start_DMA(), HAL_Delay(), LCD_Clear(), LCD_String_xy(), temperature1, and TIM2.
Referenced by preparing().