MaquinaBebidas: Core/Src/modules.c File Reference
modules.c File Reference
#include "main.h"
#include "lcd.h"
#include "core.h"
Macros
#define ADC_SCALE (3.3/4095)
#define MAX_DUTY_CYCLE_VALUE 4000
#define DEGREE_CONVERSION 0.005
#define CONVERSION 16
Functions
void add_water (int time, int type)
void add_co2 (int time)
void heater (float desired_temperature, ADC_HandleTypeDef *hadc1)
void cooler (float desired_temperature, ADC_HandleTypeDef *hadc1)
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
Variables
uint32_t adcData [16]
float adc1
float temperature1
float adc2
float temperature2
uint32_t dutyCycle = 0
uint32_t flag = 0
Macro Definition Documentation
ADC_SCALE
#define ADC_SCALE (3.3/4095)
Definition at line 12 of file modules.c.
CONVERSION
#define CONVERSION 16
Definition at line 15 of file modules.c.
DEGREE_CONVERSION
#define DEGREE_CONVERSION 0.005
Definition at line 14 of file modules.c.
MAX_DUTY_CYCLE_VALUE
#define MAX_DUTY_CYCLE_VALUE 4000
Definition at line 13 of file modules.c.
Function Documentation
add_co2()
void add_co2 (int time)
Definition at line 45 of file modules.c.
References GPIO_PIN_1, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), and LCD_String_xy().
Referenced by preparing().
add_water()
void add_water (int time, int type)
Definition at line 22 of file modules.c.
References dutyCycle, GPIO_PIN_0, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOB, HAL_Delay(), HAL_GPIO_WritePin(), LCD_String_xy(), and TIM2.
Referenced by preparing().
cooler()
void cooler (float desired_temperature, ADC_HandleTypeDef * hadc1)
Definition at line 92 of file modules.c.
References adc2, ADC_SCALE, adcData, CONVERSION, DEGREE_CONVERSION, flag, hadc1, HAL_ADC_Start_DMA(), HAL_Delay(), LCD_Clear(), LCD_String_xy(), temperature2, and TIM2.
Referenced by preparing().
heater()
void heater (float desired_temperature, ADC_HandleTypeDef * hadc1)
Definition at line 52 of file modules.c.
References adc1, ADC_SCALE, adcData, CONVERSION, DEGREE_CONVERSION, flag, hadc1, HAL_ADC_Start_DMA(), HAL_Delay(), LCD_Clear(), LCD_String_xy(), temperature1, and TIM2.
Referenced by preparing().
Variable Documentation
adc1
float adc1
Definition at line 18 of file modules.c.
Referenced by heater().
adc2
float adc2
Definition at line 19 of file modules.c.
Referenced by cooler().
adcData
uint32_t adcData[16]
Definition at line 17 of file modules.c.
Referenced by cooler(), and heater().
dutyCycle
uint32_t dutyCycle = 0
Definition at line 20 of file modules.c.
Referenced by add_water().
flag
uint32_t flag = 0
Definition at line 20 of file modules.c.
Referenced by cooler(), HAL_ADC_ConvCpltCallback(), and heater().
temperature1
float temperature1
Definition at line 18 of file modules.c.
Referenced by heater().
temperature2
float temperature2
Definition at line 19 of file modules.c.
Referenced by cooler().